### ISSUE TITLE
issue : sanctuary.fr

### ISSUE THREAD

**Issue by Telev78** [easylist/listefr#100]
Hello,

Please remove this [filter](https://github.com/easylist/listefr/commit/349123018423f53c24e12338d83eb582e29e5c56). I'm a user of this site, and this filter break many fonctionality.

Regards,

**Comment by smed79** [comment]
Bonjour, 

> break many fonctionality

Pages exemple, fonctionnalités cassées, comment reproduire?

**Comment by Telev78** [comment]
par exemple lors de l'ajout d'un item dans la collection, il est possible de choisir le lieu d'achat dans une liste.
Cette liste ne s'affiche pas quand le filtre est actif.
Même genre de problème lors de l'ajout d'une dédicace à sa collection. La liste des auteurs ne s'affiche pas.
En fait dès que le site fait un appel un script, le script ne fonctionne pas a cause du filtre

**Comment by smed79** [comment]
Merci générer un [rapport](https://help.eyeo.com/en/adblockplus/report-an-issue?) Adblock Plus et poster le lien ici.

**Comment by smed79** [comment]
https://github.com/easylist/listefr/commit/5749c2130bc8389b308baa71ac7ab6f3c59366e2
