### ISSUE TITLE
[cdn77] netspotapp.com

### ISSUE THREAD

**Issue by Quorum75** [easylist/listefr#102]
Netspot application (`www.netspotapp.com`) update doesn't work because the list blocks cdn.netspotapp.com.

It should be whitelisted as it is a false positive.

Screenshot 
- https://user-images.githubusercontent.com/49731083/198301146-31d7d834-10d5-43dc-8330-29b1c5f6cc89.png

**Comment by smed79** [comment]
Hi, 

`1650332981.rsc.cdn77.org` is not blocked in **liste FR** same as `cdn.netspotapp.com`

see https://github.com/easylist/listefr/issues/82

**Comment by Quorum75** [comment]
So, you are telling me NextDNS screenshot is wrong?

**Comment by smed79** [comment]
The **ListeFR** is a list of ad filters intended for use with ad blockers that support the **Adblock Plus** [filter syntax](https://help.adblockplus.org/adblock-plus-help-center/how-to-write-filters).

Good if it is formatted for **dns blocking** but if a filter is interprets **wrongly** it is not our fault.

Report your issue https://github.com/nextdns/metadata/issues/492

**Comment by Quorum75** [comment]
In fact cdn77.org appears twice in the list. This is why it is blocked.

**Comment by smed79** [comment]
DNS blocking have its limitations and can cause FP, as a workaround should have whitelist list.

**UHB** whitelist list https://github.com/Ultimate-Hosts-Blacklist/whitelist is a good example.

The issue should be fixed NextDNS side.

Thank you for your understanding.
