### ISSUE TITLE
github.io

### ISSUE THREAD

**Issue by traffaillac** [easylist/listefr#104]
Bonjour,

Depuis le commit [4ceb8a7](https://github.com/easylist/listefr/commit/4ceb8a7b38a10f74eac3546a6521df5caa4b4330) tous les sous-domaines de github.io sont bloqués (ex. https://square.github.io/). C'est voulu ?

Merci pour votre travail !
Thibault Raffaillac

**Comment by smed79** [comment]
Bonjour, 

faux positif, résolu ici  https://github.com/easylist/listefr/commit/22904e9265a27eba6296ed31dfcc0b6e49d2cc97

Désolé pour la gène occasionné :pray:
