### ISSUE TITLE
taobao.com

### ISSUE THREAD

**Issue by alex-kinokon** [easylist/listefr#105]
Bonjour,

Depuis [ce commit](https://github.com/easylist/listefr/commit/4ceb8a7b38a10f74eac3546a6521df5caa4b4330) taobao.com est complètement bloqué.

**Comment by smed79** [comment]
Bonjour,
Le problème a été réglé, votre liste de filtre se mettra automatiquement à jour.

Merci d'avoir pris le temps de le signaler.
