### ISSUE TITLE
[NSFW] Slutroulette.com

### ISSUE THREAD

**Issue by crak-mbelanger** [easylist/listefr#106]
Bonjour,

Noter que les liens suivants sont NSFW - Contenus adulte

Nom du site: `slutroulette.com`

Site principalement anglophone mais avec sous domaine fr `fr.slutroulette.com`

Le domaine n'est pas sur la EasyList US mais apparait 3 fois sur la Easylist FR

```
||slutroulette.com^$third-party
||slutroulette.com^$popup,third-party
||slutroulette.com^
```

Nous comprenons les flags third-party et adblock étant donner que nous plaçons des publicités qui pointent vers ce site. Cependant, le flag ||slutroulette.com^ brise la grande majorité du site (feed, images, css javascripts, login, etc)

Exemple d'url bloqués qui brise le fonctionnement du site:

```
https://slutroulette.com/theme.min.css
https://slutroulette.com/_ilc/client.js
https://slutroulette.com/generic-page/overlay-18/rta.svg
```

Nous n'avons pas de pubs / ad servers sur le site et nous n'asseyons pas non plus de contourner adblock.

Merci

**Comment by smed79** [comment]
Bonjour, 

déjà résolu ...

Merci pour le signalement.
