### ISSUE TITLE
1278313086.rsc.cdn77.org

### ISSUE THREAD

**Issue by Quorum75** [easylist/listefr#109]
When I manually update iOS AdGuard Pro I see in my NextDNS log that Liste FR is blocking filters.adtidy.org

→ 1278313086.rsc.cdn77.org | Blocked by Liste FR.

What's happening here?

![image](https://user-images.githubusercontent.com/49731083/208241783-12a7ff70-3d2d-4f9c-ab13-31ce80e35e25.png)

**Comment by smed79** [comment]
`1278313086.rsc.cdn77.org` is NOT blocked in **liste fr**

See https://github.com/easylist/listefr/issues/82 and https://github.com/easylist/listefr/issues/102
