### ISSUE TITLE
www.automobile-propre.com

### ISSUE THREAD

**Issue by garry-ut99** [easylist/listefr#115]
Site: 
- `https://www.automobile-propre.com/`

An ad placeholder: 
- https://user-images.githubusercontent.com/72945564/214710912-9016a63b-7dc9-43a2-aaa6-48b040be99ca.png

Steps to reproduce: 

1. visit the website

Filter:

```
###optidigital-adslot-Billboard_1
```

**Comment by smed79** [comment]
Doit déjà être masqué par `##div[id^="optidigital-adslot-"]`

Le problème vient de votre coté.

**Comment by garry-ut99** [comment]
You're right, it's `ghide` from uBO filters causing it: https://github.com/uBlockOrigin/uAssets/issues/16520, pardon.
