### ISSUE TITLE
latelierdeschoix.fr

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#116]
element is being blocked on this website:

- https://user-images.githubusercontent.com/65717387/216074792-c285e486-b612-49bf-bdeb-f00cad573319.JPG
- https://user-images.githubusercontent.com/65717387/216074814-a38927f2-5d56-44b9-823a-f330190cb3b4.JPG
```
https://latelierdeschoix.fr/revenus-passifs
https://latelierdeschoix.fr/be-box-a-lula
https://latelierdeschoix.fr/par-ou-commencer
https://latelierdeschoix.fr/creer-ta-formation-artistique-en-ligne
```

Filter causing the issue:
- `||systeme.io^$~image,third-party`

**Comment by smed79** [comment]
No need to go through a marketing platform to implement a feature or a widget.

The blocking will remain applied for `systeme.io`
