### ISSUE TITLE
blick.ch

### ISSUE THREAD

**Issue by eporubin** [easylist/listefr#119]
Hi 👋 

could you please remove this specific filter from the list `blick.ch##a[rel^="sponsored"]` its hiding the button on the page and the page maintainer complained:  
> "The CTA is hidden. It's not publicity, or an add. It's a call-to-action for shopping. Can you enable this?"
The button being hidden by EL Fr: 

- https://user-images.githubusercontent.com/33602691/217519907-218cf083-979b-489e-ac41-16e29fb45d07.png

Thank you in advance

**Comment by smed79** [comment]
Hi,
ok, filter removed.

Thanks for reporting it.
