### ISSUE TITLE
blocket.se

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/listefr#12]
The page is blank due to `/myads.$domain=~myads.agency` in Liste FR. This was initially pointed out to me in https://github.com/AdguardTeam/AdguardFilters/issues/85172

Example page: `https://www.blocket.se/mina-annonser`
Adblockers: AdGuard for Chrome 3.6.6
Browser: Vivaldi 4.0.2312.24 x64
OS: Windows 10 21H1 x64

**Comment by smed79** [comment]
Fixed https://github.com/easylist/listefr/commit/1afe85d1912251d0497219e54424a1dcd111f0dd

Thank you.
