### ISSUE TITLE
salaire-brut-en-net . fr

### ISSUE THREAD

**Issue by manuel-martinez-dev** [easylist/listefr#120]
### Website:

`salaire-brut-en-net.fr`

### Issue:

Some job market website being advertised on the main page of the site.

Example page: 

`https://www.salaire-brut-en-net.fr/`

### Lists using:

ABP-antiCV
listeFR
Easyprivacy

### Settings:

- OS/version: Win 10
- Browser/version: chrome 109.0.5414
- Adblock Extension/version: 3.16.1

#### Filter suggestion:

* salaire-brut-en-net.fr##div[id*="ad-"]

aajtak.in##.rtl-shopping
#### Screenshot:

<details>
<summary>See below:</summary>

![Screenshot from 2023-02-15 10-15-41](https://user-images.githubusercontent.com/40897997/218984950-51be47aa-bdfe-4648-9e9e-74acc59fe594.png)

</details>

**Comment by smed79** [comment]
Hi, 
add https://github.com/easylist/listefr/commit/00b89d857ea97f8dd5b0a88853544f5c3e0c100b

Thank you.
