### ISSUE TITLE
klaviyo.com

### ISSUE THREAD

**Issue by nshenkman** [easylist/listefr#121]
Hello I am Engineer at Klaviyo. I believe your targeting for our JS may be too broad as it is preventing functionality on the website as demonstrated in the screenshots. We have worked hard to separate out our tracking JS from our non-tracking JS and load it via a separate subdomain. The correct targeting for tracking would be targeting `static-tracking.klaviyo.com` and `telemetrics.klaviyo.com`. Your existing targeting is preventing any of our JS from loading (tracking and non-tracking) as it is all loaded via klaviyo.com. Here are some examples of other filters (easyprivacy) using these rules:
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L1714
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L1871

To help out I have linked where I think the filter is located:
https://github.com/easylist/listefr/blob/master/liste_fr.txt#L13827
https://github.com/easylist/listefr/blob/master/liste_fr.txt#L9057

If you would like to investigate yourself the url I tested on is https://kontrolfreek.com/ but this issue persists on any website that uses Klaviyo.

With this filterlist
<img width="1840" alt="Screen Shot 2023-02-16 at 1 54 08 PM" src="https://user-images.githubusercontent.com/7377088/219460987-0c1225c7-53e0-43e7-b9b2-fcb5c2e54186.png">

uBlock Logger
<img width="1215" alt="Screen Shot 2023-02-16 at 1 53 38 PM" src="https://user-images.githubusercontent.com/7377088/219461060-a4c5ebb2-f094-4cd9-a224-09f8b5b86a6a.png">

Without this filterlist
![Working](https://user-images.githubusercontent.com/7377088/219460787-de311bd8-16e2-4036-9ab2-4aa6b5279677.jpg)

**Comment by smed79** [comment]
Hi, 

filter removed.

Thanks for reporting it.
