### ISSUE TITLE
46.149.79.15 (idlix)

### ISSUE THREAD

**Issue by eporubin** [easylist/listefr#124]
Hi, please review this popping ads banner on `https://46.149.79.15/`
This filter `46.149.79.15###repop` seems to do the job for me, thanks
- https://user-images.githubusercontent.com/33602691/226617248-1d98fbdd-8a5d-4799-81f7-d0351807d7c2.png

**Comment by smed79** [comment]
@eporubin IDLIX is an indonesian site with english contents (not a **french**) !

add
```adblock
46.149.79.15,idlix.cc,idlix.com,idlix.net###repop
||jeniusplay.com/cdn/gif/qqbanner/
```
add also 
```adblock
idlix.pro,idlix.to,idlix.wiki##.kln
```
&
```
216.250.252.7,idlix.link##[class^="idmuvi"]
```

@Khrin @ryanbr fyi.
