### ISSUE TITLE
manomano.fr

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#126]
- `https://www.manomano.fr/chaise-4588`
- https://user-images.githubusercontent.com/65717387/227230047-301b6c98-0dcc-49e7-954f-5cdcef35feaf.png

Remove sponsored ads.
```
manomano.fr#?#.c8t8QEI:-abp-has([data-testid="sponsored-brand-logo-link"])
manomano.fr#?#a[class]:-abp-has([data-testid="product-card-sponsored-label"])
```

**Comment by smed79** [comment]
Ajouté https://github.com/easylist/listefr/commit/589114e454c56a81eefc00adb83198b7006d5a3f

Merci.
