### ISSUE TITLE
Ads on `notre-siecle.com` & `perelafouine.com`

### ISSUE THREAD

**Issue by eporubin** [easylist/listefr#127]
Hi, please add the following filter to the list or please let me know why is not accepted: 
On both websites there is this ads:
![image](https://user-images.githubusercontent.com/33602691/227530052-c980ae30-af10-4298-87c8-6639bee659d8.png)
Right side (down in the content - redirects outside of scope) -->
`notre-siecle.com,perelafouine.com##div[id*="media_image"]`

**Comment by eporubin** [comment]
hi @smed79 looks like the filters you have added would just prevent the image from being placed on the website yet the redirection is still happening plus it does not look appealing 

https://user-images.githubusercontent.com/33602691/227626280-700c525c-10a1-4cb8-8818-d76d69c0c3be.mov

Please reconsider and maybe better use this one `notre-siecle.com,perelafouine.com##div[id*="media_image"]`

**Comment by smed79** [comment]
Hi,
the suggested filter `##div[id*="media_image"]` is too broad and may cause false positives.

I made a change as below https://github.com/easylist/listefr/commit/1879ea57fe0c8c161daf0bf7c5c634a64ff15d5d

Thank you.
