### ISSUE TITLE
newpharma.fr

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#128]
Banners all over the page

- `https://www.newpharma.fr/cat/beaute-cosmetiques/soins-du-visage/12-14.html`

```adblock
newpharma.fr##.c-adh-banner
```

Screenshot 
- https://user-images.githubusercontent.com/65717387/229775636-f115ce1f-04a0-4c39-a7ec-b464806c3e7a.png

**Comment by smed79** [comment]
Ajouté https://github.com/easylist/listefr/commit/a9781f2d9b6925baf6ce18905df29f6af90cde81

Merci pour le signalement.
