### ISSUE TITLE
french-stream.re

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#13]
**Website:**

* `https://french-stream.re/`

**Issue:**
Redirect popup shows up after clicking on a chapter and also after clicking on the play button.

**Lists:**

ABP filters
Liste FR+EasyList

**Instructions to reproduce:**

Go to the website `https://french-stream.re/`
click on any chapter (popup should show up)
click on the play button (popup should show up)

**Scr**

https://user-images.githubusercontent.com/57706597/124833437-76fb8300-df7e-11eb-9e9d-6eaa280511ce.png

**Suggested filter:**

-- to block popup/about:blank usually with: _i.imgur.com/6uuHn2R.jpg_

* `$popup,third-party,domain=french-stream.re`
OR
* `/$popup,third-party,domain=french-stream.re`

**Comment by smed79** [comment]
Fixed... Thank you.
