### ISSUE TITLE
sleeptimer.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/listefr#130]
Hello.

For `https://sleeptimer.org/` there are 4 filter present:

```
||sleeptimer.org^
||sleeptimer.org/playerc.js
$webrtc,domain=sleeptimer.org
$websocket,domain=sleeptimer.org
```

It seems to be they are obsolete, `sleeptimer.org/playerc.js` also throws a 404

Please take a look.

**Comment by smed79** [comment]
Hello,

removed in https://github.com/easylist/listefr/commit/385ac21ba92d030e80acf9882b32c4d0fcaa6614

Thank you.
