### ISSUE TITLE
zt-za.net

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#14]
**Issue:**
Images are hidden on `https://www.zt-za.net/index.php` when [listefr](https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt) is enabled on Adblock Plus (ABP).

https://user-images.githubusercontent.com/57706597/125326877-d1139400-e342-11eb-931c-ba83bab2a658.png

Could you please delete ``zt-za.net`` domain from this below filter or add an exception to it?

**Filter causing issue in listefr:** `,zt-za.net,...##a[href*=".php"]`

Thank you in advance.

**Comment by smed79** [comment]
Removed... Thank you.
