### ISSUE TITLE
japscan.ws

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#15]
**Issue:** Popup message on [japscan.ws](https://www.japscan.ws) (Desktop and mobile version)

**List:** EL+ListeFR
Looks like popup is being served by: **||psaukaux.net^**

Can you please have a look at it?
Thank you so much.

<img width="1341" alt="japscan" src="https://user-images.githubusercontent.com/57706597/125761629-db6c49a5-d047-4eb1-ba74-6b3d32af4d32.png">

**Comment by smed79** [comment]
https://github.com/easylist/listefr/commit/0e73c4f1ea90cb5ae1dd67b4d0919509278ca497
https://github.com/abp-filters/abp-filters-anti-cv/pull/640
