### ISSUE TITLE
vostanimes.tv

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#16]
Hi Smed,

Can you please check if you can reproduce below issue?

Issue: 

redirect popup on `vostanimes.tv` when you click on the play button for **ninjastream server**.

Sample URL

`https://vostanimes.tv/Episode/shinigami-bocchan-to-kuro-maid-vostfr-saison-1-episode-3-streaming-hd/`

Tested also on Android mobile > Adblock Browser (ABB)
List: EL and listefr

Listefr filter: `?key=*&psid=$popup` helps but does not prevent popup from opening on mobile.

Please let me know if you need more info. 
Thank you for your time.

**Comment by smed79** [comment]
Hi, 

The popup seems blocked for me, tested here `ninjastream.to/watch/goVAd0arRAJnE`

Please, update your filter lists and test again.

**Comment by edivaniadc** [comment]
Hello Smed,

Thanks for having a look at it. 

Regarding Ninja I could still reproduce it on Adblock Browser (ABB) - on Android mobile. In case you have the chance to test it in there please, just to see if you get the same in there (tested with FR VPN).
<img width="365" alt="abb" src="https://user-images.githubusercontent.com/57706597/127470410-1097e714-950d-4f28-9849-b7790b0955a8.png">


I've also noticed that filter `$script,third-party,domain=1377x.to|1anim.com...` adjusted on commit: [a1c5413](https://github.com/easylist/listefr/commit/a1c5413) that has **vostanimes.tv** as one of the domain is blocking the play button for **Ddl-francais VOSTFR - FHD** server and for some titles this server is the only option available to watch [example](https://vostanimes.tv/Episode/stella-no-mahou-magic-of-stella-vostfr-saison-1-episode-11-streaming-hd/)
<img width="1349" alt="Ddl" src="https://user-images.githubusercontent.com/57706597/127470447-d5b2dc59-3914-4c05-94c0-f04b2e9949ee.png">

**Comment by Yuki2718** [comment]
@ryanbr `||cfeucdn.com^` in EL breaks video here.

**Comment by smed79** [comment]
@Yuki2718 Fixed https://github.com/easylist/listefr/commit/fc3d41f1a6c23e4a5a40448ea0aec8378dadd1e1
