### ISSUE TITLE
toonanime.tv

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#17]
Hi there,

Can you please block a redirect popup on [toonanime.tv](https://toonanime.tv/)

It happens right after you select one of the chapters and it opens `https://toonanime.tv/templates/toonanime/images/logo.png` and then redirects to other websites such as: gearbest.com., bestwnnrsp.click...

Possible filter: `||toonanime.tv/templates/toonanime/images/logo.png$popup`
_Please note that needs to have the $popup, otherwise is going to hide the website logo._
This is mainly to be fixed on mobile since snippet filter doesn't work there.

Thank you in advance.

**Comment by smed79** [comment]
Bonjour, 

filtre ajouté https://github.com/easylist/listefr/commit/520f0f51412ec8fe43868b7743b7f039c5557470
