### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by mjethani** [easylist/listefr#18]
https://github.com/easylist/listefr/blob/ea5603e7df929b3618c1d6e132456eba3b0dcb7f/liste_fr.txt#L17897

[Cliqz](https://cliqz.com/en/whycliqz/adblocking) rejects such filters.

Is it possible to remove the comma at the beginning?

You can [lint your filters](https://github.com/mjethani/flint):

```
npm i -g flint-tool
flint listefr/liste_fr.txt
```

**Comment by mjethani** [comment]
You can [lint your filters](https://github.com/mjethani/flint):

```
npm i -g flint-tool
flint listefr/liste_fr.txt
```

**Comment by smed79** [comment]
Fixed https://github.com/easylist/listefr/commit/6da00efcfbc7ca4c3675ffd7d8599c15c4f02a0a, Thank you.
