### ISSUE TITLE
leboncoin.fr

### ISSUE THREAD

**Issue by fds39** [easylist/listefr#183]
Bonjour,
Depuis 1 semaine l'accès à `leboncoin.fr` est <i>précaire*</i> si aucun numéro de téléphone n'a été renseigné. Si l'on filtre ce popup la page est visible mais non cliquable. 

<i>*en supprimant 'accueil' de l'url (cf capture) on accède au site (sauf à la partie 'compte' qui perpétuellement affichera le popup)</i>

Alors existe-t-il une solution pratique pour se débarrasser de ce satané popup ? 

Merci.

Capture d’écran :  ~ image supprimée ~

**Comment by fds39** [comment]
Bonjour,
Merci d'avoir pris la peine de répondre. Pour un compte test il n'y a pas le choix : par définition ce doit être un compte déjà créé, car à ce jour une inscription doit obligatoirement être associé à un n° de tel. En conséquence c'est mon compte perso qui fera office de compte test. Je dois donc vous communiquer mes ID + mdp. Voudriez-vous m'indiquer comment vous les transmettre en mp ?

**Comment by fds39** [comment]
Entendu. 
Je viens de faire un test d'inscription d'un nouveau compte leboncoin et ça fonctionne à priori avec tutamail (ex tutanota). Je dis à priori car j'ai bien reçu la confirmation sur mon compte tutamail fraichement créé pour l'occasion, mais je n'ai pas pu finaliser la création du compte leboncoin en raison de l'étape 'demande de n° de tel'.

**Comment by smed79** [comment]
Désolé de n'avoir pu vous aider ici.
