### ISSUE TITLE
allosurf.net

### ISSUE THREAD

**Issue by gut1414** [easylist/listefr#199]
Ce site se mets à l'anti-adblock, impossible à contourner.

**Comment by smed79** [comment]
v

**Comment by gut1414** [comment]
Continue de bloquer les adblocks, malgré votre nouveau filtre.

**Comment by smed79** [comment]
Filtre ajouté a "**Adblock Warning Removal List**" et non pas sur la "**liste FR**".

**Comment by gut1414** [comment]
Ok merci.
