### ISSUE TITLE
ianimes.org

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#20]
Hi there Smed,
Hope all is well with you.

May I ask you please if you can block some redirect popups on **ianimes.org**

It happens mainly when you click on the play button for **Doodstream** (dood.ws), **Streamz** (streamzz.to) and **UpStream** servers.

URLs:

```
https://www.ianimes.org/a79cf208ad3d289a16cea551316fa39a.htm
https://www.ianimes.org/0bed45bd5774ffddc95ffe500024f628.htm
```

[https://user-images.githubusercontent.com/57706597/135755567-5b41743c-5a1a-42e9-bb4b-d13f8a88fd57.png](https://user-images.githubusercontent.com/57706597/135755567-5b41743c-5a1a-42e9-bb4b-d13f8a88fd57.png)

[https://user-images.githubusercontent.com/57706597/135755596-d1c556bc-7fb0-4e64-b4f0-2aebc5d0954e.png](https://user-images.githubusercontent.com/57706597/135755596-d1c556bc-7fb0-4e64-b4f0-2aebc5d0954e.png)

Thank you in advance.

**Comment by edivaniadc** [comment]
Hello @smed79, hope all is well with you. When you have the chance can you please test with: `about:blank$popup,domain=ianimes.org|dood.ws|vizplay.icu|streamzz.to` it seems to block redirects for the other servers^ but for some reason still not blocking for **Doodstream**

**Comment by smed79** [comment]
> do you think is it possible still to fix the redirect popup on Doodstream (dood.ws) server?

https://github.com/abp-filters/abp-filters-anti-cv/pull/706
