### ISSUE TITLE
ecranlarge.com

### ISSUE THREAD

**Issue by CultureG** [easylist/listefr#201]
Hello,

Site's own scripts are blocked from ecranlarge.com.  The rule `||ecranlarge.com/*?$script` seems to be to generic an blocks URLs like:

`https://www.ecranlarge.com/content/themes/ecran-large/assets/js/frontend/lib/jquery-4.0.0-beta.min.js?ver=4.0.0`

**Comment by smed79** [comment]
Hi, 

> Site's own scripts are blocked

that filter was previously added because of the first party revolving ad scripts which seems to be disabled now.

... filter removed in https://github.com/easylist/listefr/commit/9b31af31ecb3e054b9eada6a696563fd49ed1229

Thank you.
