### ISSUE TITLE
candy.ai

### ISSUE THREAD

**Issue by Yanneverai** [easylist/listefr#203]
Bonjour, pourriez vous retirer la règle
`||candy.ai^$popup,third-party`

Avec cette règle actuelle, Candy est bloqué pour tous les utilisateurs qui ont un adblock
Ils ne peuvent plus accèder aux emails que nous envoyons à nos utilisateurs français, comme l'email de vérification.

https://github.com/easylist/listefr/assets/172542373/d67e023e-ebc5-4945-b778-d9421a508095

"The filter was "killed" in the adguard french list (used by uBlock Origin and AdGuard adblockers)"
https://github.com/AdguardTeam/AdguardFilters/commit/acbe77d2d56d0aa42d78de78ba82d831158c5a6d

Intense m'a recommandé de poster ici pour gérer les autres adblockers.

Merci bien.

**Comment by smed79** [comment]
Bonjour,

Je vous recommande de régler ce problème avec votre client "japscan" qui abuse pour forcer l'affichage de votre publicité.

Merci pour votre compréhension.

**Comment by Yanneverai** [comment]
Bonjour, c'est un affilié, nous n'avons pas la main sur ses moyens de promotions, nous n'avons rien contre le fait de bloquer les publicités, mais dans ce cas précis cela empeche nos utilisateurs de valeur leur email, est il possible de remplacer la règle générique par une règle qui ne concernerait que japscan ? merci

**Comment by smed79** [comment]
Je vous crois sur parole ==> filtre supprimé.

... Mais si un abus nous est signalé, je restaurerai le filtre sans hésitation.
