### ISSUE TITLE
wiflix-catalogue.pro

### ISSUE THREAD

**Issue by fiketek** [easylist/listefr#205]
bonjour,
plusieurs options sur mon site sont blockés avec ublock, comme les favoris, le profil des utilisateurs et quelques players 
vous pouvez retirez les filtres de mon site?
merci et bonne journée

**Comment by smed79** [comment]
Bonjour, 

J'ai supprimé le filtre incriminé... 

_mais si vous contournez à nouveau le blocage, ne vous attendez pas à ce que nous vous aidions_.

Merci pour votre compréhension.

**Comment by fiketek** [comment]
Bien sûr, voici une version corrigée et reformulée de votre phrase :
------------------------------

Bonjour Smed,

Je n'ai pas une grande connaissance du contournement des adblocks, mais
vous pouvez ajouter des filtres pour les pop-ups, tout en conservant les
options du site intactes. Plusieurs membres ont dû désinstaller uBlock pour
accéder à tous les services du site. Ce qui m'intéresse vraiment, c'est
l'option permettant aux visiteurs de mettre un film ou une série en favori
(voir capture 1) et le player intégré à notre charte graphique (voir
capture 2).

Je vous remercie infiniment

**Comment by fiketek** [comment]
Salut Smed,

Merci pour les dernières corrections concernant les filtres. J’ai une
demande : serait-il possible d'exclure les trois boutons (Regarder,
Télécharger et Voir film) de ces filtres ? En réalité, ce ne sont pas des
pop-ups, mais des boutons publicitaires facultatifs, donc ils ne nuisent
pas à la navigation sur mon site. Comme tu le sais, les sites ont besoin de
quelques revenus pour vivre et couvrir leurs charges. Merci d'avance

Cordialement,

Le sam. 27 juil. 2024 à 22:19, Wiflix Streaming ***@***.***> a
écrit :

> Bien sûr, voici une version corrigée et reformulée de votre phrase :
> ------------------------------
>
> Bonjour Smed,
>
> Je n'ai pas une grande connaissance du contournement des adblocks, mais
> vous pouvez ajouter des filtres pour les pop-ups, tout en conservant les
> options du site intactes. Plusieurs membres ont dû désinstaller uBlock pour
> accéder à tous les services du site. Ce qui m'intéresse vraiment, c'est
> l'option permettant aux visiteurs de mettre un film ou une série en favori
> (voir capture 1) et le player intégré à notre charte graphique (voir
> capture 2).
>
> Je vous remercie infiniment
>

**Comment by smed79** [comment]
Bonjour, 
La liste de blocage est là pour bloquer les publicités de toutes sortes, nous n'avons pas de modèle publicitaire acceptable et nous ne faisons pas d'exceptions.

Si vous pensez que la publicité à laquelle vous faites référence relève de la publicité acceptable, je vous recommande de consulter le modèle de [publicité acceptable](https://adblockplus.org/fr/acceptable-ads) dans Adblock Plus.

Cordialement,

**Comment by smed79** [comment]
https://github.com/easylist/listefr/issues/239

**Comment by fiketek** [comment]
Bonjour Smed,

J'ai plusieurs options bloquées par uBlock sur mon site wiflix-pro.mom,
comme les favoris, l'édition, Edit ajouts, etc.

J'ai aussi une question concernant les boutons publicitaires, comme
"Regarder" et "Télécharger". Ces boutons ne demandent qu'une inscription
par e-mail, et je pense que c'est légal et correct, non ?

**Comment by fiketek** [comment]
bonjour smed, j'ai le meme probleme avec mon nouveau domaine wiflix-pro.mom, vous pouvez supprimé le filtre incriminé?

merci d'avance

**Comment by fiketek** [comment]
Bonjour Smed,
Depuis hier, je rencontre un gros problème sur mon nouveau domaine :
https://wiflix-max.cloud. Les visiteurs utilisant Google Chrome ne
parviennent plus à afficher les lecteurs. J’ai joint une capture d’écran
pour illustrer le souci.
Apparemment, ils doivent désactiver uBlock pour pouvoir accéder au contenu.
Pourriez-vous regarder ça et voir si une solution est possible ?
Merci d’avance pour votre aide !

**Comment by fiketek** [comment]
visiblement le probleme c'est avec le lecteur do7go.com qui est bloqué par
adblock, pourcela les autres lecteurs ne s'affichent plus

Le dim. 20 avr. 2025 à 07:13, Wiflix Streaming ***@***.***> a
écrit :

> Bonjour Smed,
> Depuis hier, je rencontre un gros problème sur mon nouveau domaine :
> https://wiflix-max.cloud. Les visiteurs utilisant Google Chrome ne
> parviennent plus à afficher les lecteurs. J’ai joint une capture d’écran
> pour illustrer le souci.
> Apparemment, ils doivent désactiver uBlock pour pouvoir accéder au
> contenu. Pourriez-vous regarder ça et voir si une solution est possible ?
> Merci d’avance pour votre aide !
>

**Comment by fiketek** [comment]
hi mon ami, désolé pour le dérangement, j'ai changé le domaine  do7go.com
jusqu'a vous vérifié cela, merci d'avance

Le dim. 20 avr. 2025 à 07:39, Wiflix Streaming ***@***.***> a
écrit :

> visiblement le probleme c'est avec le lecteur do7go.com qui est bloqué
> par adblock, pourcela les autres lecteurs ne s'affichent plus
>
> Le dim. 20 avr. 2025 à 07:13, Wiflix Streaming ***@***.***>
> a écrit :
>
>> Bonjour Smed,
>> Depuis hier, je rencontre un gros problème sur mon nouveau domaine :
>> https://wiflix-max.cloud. Les visiteurs utilisant Google Chrome ne
>> parviennent plus à afficher les lecteurs. J’ai joint une capture d’écran
>> pour illustrer le souci.
>> Apparemment, ils doivent désactiver uBlock pour pouvoir accéder au
>> contenu. Pourriez-vous regarder ça et voir si une solution est possible ?
>> Merci d’avance pour votre aide !
>>

**Comment by smed79** [comment]
Bonjour @fiketek;

Problème causé par un filtre ajouté sur EasyList et non pas la Liste FR.

J'ai fait un signalement ici https://github.com/easylist/easylist/pull/21677

Merci d'avoir prit le temps pour signaler le problème.

**Comment by fiketek** [comment]
merci smed, le probleme concerne le domaine ( do7go.com) c'est un domaine
qui appartient a doodstrem (lecteur video)

merci infiniment

**Comment by smed79** [comment]
> le probleme concerne le domaine `do7go.com`

Le filtre a été supprimé https://github.com/easylist/easylist/commit/0b9cc667b79675d52195c0ae1b52ea7d5c45294b
