### ISSUE TITLE
[NSFW] nijisenmon.work

### ISSUE THREAD

**Issue by Yuki2718** [easylist/listefr#209]
`##.widget.ad` is hiding side-bar.

**Comment by Yuki2718** [comment]
Hm, I don't know why I missed the rule is in EL. But it seems the rule is problematic, the same problem on e.g. `http://ironsaga-msoku.xyz/`, `https://takushoku.info/`.

**Comment by Khrin** [comment]
@smed79 Do you have any objections to the removal of this rule present in Liste FR? `##.widget.ad` Seems to cause several false positives and the same rule has been removed from EasyList.
