### ISSUE TITLE
planet.fr

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#21]
**Issue:** 

Block ads on planet.fr (bottom of the page > SERVICES)

**URL:** 

`https://www.planet.fr`

**Filter suggestion:** 

`planet.fr##div[id^="ABTastyElement"]`

**Screenshot:**

[https://user-images.githubusercontent.com/57706597/138726894-b72ba43b-a9ca-4a1c-a2a7-9485e35edf8b.png](https://user-images.githubusercontent.com/57706597/138726894-b72ba43b-a9ca-4a1c-a2a7-9485e35edf8b.png)

**Comment by smed79** [comment]
Ajouté https://github.com/easylist/listefr/commit/69a76c639c3097775d6214c0cddebd854cbc334a
