### ISSUE TITLE
ecranlarge.com

### ISSUE THREAD

**Issue by CultureG** [easylist/listefr#211]
Hello,

Cette ligne :
`$script,third-party,domain=ecranlarge.com` (et plein d'autres domaines) dans la liste FR - EasyList bloque de nombreux scripts externes utiles à la navigation, y compris par exemple les appels à Stripe (`js.stripe.com`) utilisés pour que les visiteurs puissent s'abonner au site. 

Il me semble que toutes les pub du site passent par des adserveurs classiques déjà bloqués par d'autres règles, donc je ne comprends pas l'objectif de cette règle. Est-il possible de retirer ecranlarge.com de cette règle ?

Merci.

**Comment by smed79** [comment]
Bonjour,

Ce filtre a été ajouté précédemment en raison du contournement des publicités `/proxy/pub/.../bg.php?`

Contourner le blocage justifie le blocage strict.

**Comment by CultureG** [comment]
Bonjour,

Il n'y a plus de script de ce type depuis très longtemps (et pas de projet d'en remettre), donc la règle ne sert plus à rien.

Actuellement cette règle bloque en particulier Stripe qui permet aux gens de soutenir financièrement le site par un autre moyen que la pub justement.

**Comment by smed79** [comment]
Bonjour,

filtres supprimés https://github.com/easylist/listefr/commit/530e74c0505dddd72a9e92bebd08bf2b119ad0ae


Merci pour le signalement.
