### ISSUE TITLE
Selector introduced in https://github.com/easylist/listefr/issues/212 is invalid

### ISSUE THREAD

**Issue by ucanfil** [easylist/listefr#216]
Our Sentry is spammed with:

```
Failed to execute 'matches' on 'Element': 'a[href^="href="https://secured.lol/"]' is not a valid selector.
```

that's how we figured out the issue. Not sure which but it seems like some of the adblockers are not great at catching errors on their end.

**Comment by smed79** [comment]
Hi,

Typo fixed.

Thanks for reporting it.
