### ISSUE TITLE
(NSFW) xhamster bait

### ISSUE THREAD

**Issue by Yuki2718** [easylist/listefr#219]
`/affiliate/*/banners/*` is baited on xhamster as of writing:

<details>
<summary>Screenshot</summary>

![bait](https://github.com/user-attachments/assets/0a119604-1183-4422-a7af-0948dd2d14ec)

</details>

Though it may change tomorrow, can you consider either removing the rule or excluding `xmlhttprequest`?

**Comment by Yuki2718** [comment]
Now it's `/banner-ads`

<details>
<summary>Screenshot</summary>

![bait](https://github.com/user-attachments/assets/2931efb9-e77a-4218-8e03-d4a7c83ca9b6)

</details>

**Comment by Yuki2718** [comment]
<details>
<summary>Screenshot</summary>

![banner-ads](https://github.com/user-attachments/assets/3b6cba45-f2e6-418d-92dc-7a0e39d95805)

</details>

**Comment by Yuki2718** [comment]
`/ad/*/728/*` and `/thirstyaffiliates/*`
<details>
<summary>Screenshots</summary>

![xh-bait](https://github.com/user-attachments/assets/4dee5d4e-650d-42af-8e97-0d6663ac1143)

![xh-bait2](https://github.com/user-attachments/assets/a48d1147-974b-48f5-8967-dab27e0e0f73)

</details>

If I understand correctly, Liste FR was once a standalone list, but now is a supplement for EL. If so, maybe needs cleanup of old generic rules?

**Comment by Yuki2718** [comment]
`/ad/ads.`

<details>
<summary>Screenshot</summary>

![xh](https://github.com/user-attachments/assets/eea98e35-ce31-401d-961d-593ade5aec7e)

</details>

**Comment by Yuki2718** [comment]
`/adscontroller.`

<details>
<summary>Screenshot</summary>

![xh](https://github.com/user-attachments/assets/81ae806c-e39b-46dd-a321-e492ba7d6001)

</details>

**Comment by Yuki2718** [comment]
At least `/thirstyaffiliates/*` is redundant with EL's `/plugins/thirstyaffiliates/*$script,stylesheet`.

**Comment by smed79** [comment]
I cleaned all redundant filters here https://github.com/easylist/listefr/commit/907d2215403a32677139cc0b8e7f242d27223ae7

Thank you.

**Comment by Khrin** [comment]
> I don't think I need to remove all the filters they use for adblock detection (_especially on a site like this_).

Are you sure about that? Especially on these sites it's probably best to avoid any possible detection. Also, does Liste FR need so many generic filters?

**Comment by smed79** [comment]
I said that because i think they will use new filters for bait for each filter removed and if we follow their logic, we are going to end by removing all filters.

Anyway, I am planning to do more cleaning this week. If you have any suggestions for filter removal, send it in private via email and i will check.

Thank you in advance.
