### ISSUE TITLE
hdss.la

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#22]
**Issue:** 

Unblock video frame on **hdss.la**

**Sample URL:**

 `https://hdss.la/romance-et-pierres-precieuses/`

**Filter causing issue:** 

`||redirect-ads.com^$third-party`

**Filter suggestion:** 

`@@||geoip.redirect-ads.com^$subdocument,third-party,domain=hdss.la`

After testing with allowing rule you may get an adblock wall (click on the play button), otherwise video will display normally.

_If doesn't work please try manually disabling `$script,third-party,domain=1377x.to| ...` since it has domain **hdss.la**_

**Screenshot:**

[https://user-images.githubusercontent.com/57706597/139345605-02833f79-2906-465a-8bd5-f971ea0747e4.png](https://user-images.githubusercontent.com/57706597/139345605-02833f79-2906-465a-8bd5-f971ea0747e4.png)

[https://user-images.githubusercontent.com/57706597/139345623-330eceaf-8944-473c-a444-72f949d0ab98.png](https://user-images.githubusercontent.com/57706597/139345623-330eceaf-8944-473c-a444-72f949d0ab98.png)

[https://user-images.githubusercontent.com/57706597/139350131-a4c99abf-86d9-44aa-b9d6-754279ab7364.png](https://user-images.githubusercontent.com/57706597/139350131-a4c99abf-86d9-44aa-b9d6-754279ab7364.png)

**Comment by smed79** [comment]
Access is denied to hdss.la https://i.ibb.co/0cxhvKB/image.jpg

I will double-check later...

**Comment by edivaniadc** [comment]
Hi there @smed79 just wondering if you were able to reproduce this case please?

**Comment by smed79** [comment]
Bonjour, 

problème on reproductible.

**Comment by edivaniadc** [comment]
Hi @smed79 when you have the chance can you please test manually disabling rule: `$script,third-party,domain=1377x.to|`  video player is still blocked. Thank you so much.

<img width="1282" alt="hls" src="https://user-images.githubusercontent.com/57706597/143901933-490d5333-1f4d-49eb-a439-a5a6fdcb4ca7.png">

**Comment by smed79** [comment]
I still cannot reproduce the issue.

Test if this help https://github.com/easylist/listefr/commit/c7362773f84552af697a8d4e0088194796b78c07

**Comment by edivaniadc** [comment]
> I still cannot reproduce the issue.
Can you please try with German or Hungarian VPN (Tested with ExpressVPN).

> Test if this help [c736277](https://github.com/easylist/listefr/commit/c7362773f84552af697a8d4e0088194796b78c07)
I'm no longer getting hit of `||redirect-ads.com^$third-party` which means the allowing rule won't work out in this case.

It looks like is really because of `$script,third-party,domain=1377x.to` that has hdss.la added as a domain and block the iamcdn player.
Possible filter: `@@||iamcdn.net/players/embed.js$domain=hdss.la` 

<img width="1245" alt="hsd" src="https://user-images.githubusercontent.com/57706597/144061759-ff2b133a-2ab8-46a4-b8f5-36402d203a87.png">
