### ISSUE TITLE
typo dans la liste FR  (adf vs ads)

### ISSUE THREAD

**Issue by joelmar** [easylist/listefr#220]
Bonjour

J'ai remarqué un typo qui me chagrinait depuis un moment

**assets/adf-** au lieux de **assets/ads-**

https://github.com/easylist/listefr/blob/master/liste_fr.txt#L1026C1-L1026C13

Serait possible de corriger cella de manière á que les **ads** soit correctement bloqué ?

Cordialement

**Comment by smed79** [comment]
Bonjour, 

merci d'avoir signalé cela, mais ce n'est pas une faute de frappe.

c'est un raccourcissement de `ad format`.

Cordialement
