### ISSUE TITLE
extreme-down.plus

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#24]
### Issue: 
Popup message on `https://www.extreme-down.plus/home.html`
They seem to be blocked by rule `||aiharsul.net^` (when you click on it simply disappear), but the images are still showing up. 

### Steps to reproduce:
FR VPN
ABP List + ListFR + Acceptable Ads
### Suggestion:
```
||aiharsul.net^$popup
extreme-down.plus##iframe[style*="position: fixed !important;"] 
OR extreme-down.plus##iframe[style*="z-index:"]
```

### Screenshot
https://user-images.githubusercontent.com/57706597/142244544-85cecdc4-c789-45cb-8342-efb9f0ff75f6.png
https://user-images.githubusercontent.com/57706597/142245032-91219aef-6c3f-412c-a083-e71020f8aa2b.png

**Comment by smed79** [comment]
https://github.com/easylist/listefr/commit/d3d2a97ff5d600b33841f3a259b43b92916d66aa
