### ISSUE TITLE
images are being blocked by Easylist/listeFR (false positive)

### ISSUE THREAD

**Issue by manuel-martinez-dev** [easylist/listefr#3]
**Website:**
https://www.aluson-eclairage.fr/

**Exampled page:**
https://www.aluson-eclairage.fr/autre-format-de-dalle-led/4589-dalle-led-clareo-120x60-access-6-60w-sans-alim.html

**Lists used:**
Easylist
ABP filters
EasyPrivacy
Fanboy's Social Blocking List

*it also happens when changing to ListeFR*

**Settings:**
OS/version: Lubuntu 20.04
Browser/version: Version 86.0.4240.111 (Official Build) (64-bit), firefox Version 82.0 (64-bit)
Adblock Extension/version: Adblock Plus Version 3.9.5

**Filter causing the issue:**

`-120x60-`

**Filter suggestion:**

`@@-120x60-$image,domain=aluson-eclairage.fr`

**Comment by smed79** [comment]
Bonjour;

problème résolu ici https://github.com/easylist/listefr/commit/555f0129decf7d200fdf506e3c0e0e983b48660a

Merci pour le signalement.
