### ISSUE TITLE
abo.nicematin.com

### ISSUE THREAD

**Issue by Axelnm** [easylist/listefr#30]
Notre module de paiement ne s'affiche pas sur la page `https://abo.nicematin.com/checkout` lorsque Adblock est activé.

Ci-dessous le problème : 

nicematin.com fait partie d'une liste utilisée par les adblocer : https://github.com/easylist/listefr/blob/master/liste_fr.txt
dans cette liste se trouve Nicematin, ce qui engendre donc un blocage des scripts et cookies présents sur le site.

Nous avons isolé la ligne qui pose problème :
- En vert les sites concernés par la règle
- En bleu les types de documents concernés par la règle
- En rouge les domaines/sous-domaines en liste blanche
- En rose "nicematin.com"

[https://user-images.githubusercontent.com/96480761/146938078-3c3bae13-6902-450e-a76d-a29a92f46db5.png](https://user-images.githubusercontent.com/96480761/146938078-3c3bae13-6902-450e-a76d-a29a92f46db5.png)

Merci

**Comment by smed79** [comment]
Problèmes résolu.

- https://github.com/easylist/easylist/pull/10205
- https://github.com/easylist/listefr/commit/cb0e947acd371080b4833425e5438a8b523313a0

Merci pour le signalement.

**Comment by Axelnm** [comment]
Bonjour,

Le problème persiste de mon côté, le module de paiement est toujours masqué
par Adblock

Merci

*Axel Micheau*

*Chargé de Marketing DigitalPôle connaissance & **activation marketing*
*Bâtiment Unity - Grand Arénas, **06200 Nice*
*06 24 35 79 23*

<https://www.nicematin.com/>  <https://www.varmatin.com/>
<https://www.monacomatin.mc/>

   <http://nicematin.com/>   <http://varmatin.com/>
<http://monacomatin.mc/>
<https://www.linkedin.com/company/groupenicematin/mycompany/>
<https://twitter.com/Nice_Matin>   <https://www.facebook.com/Page.NiceMatin>

**Comment by smed79** [comment]
La liste de filtre sur le serveur `[easylist-downloads.adblockplus.org](https://easylist-downloads.adblockplus.org/liste_fr.txt)` prend un moment pour se mettre à jour.

tester avec la liste héberger sur github https://raw.githubusercontent.com/easylist/listefr/master/liste_fr.txt

Pour info, j'ai aussi soumis un [pull request](https://git.io/JDhh5) pour résoudre un problème avec [Fanboy Annoyances List](https://www.fanboy.co.nz/fanboy-problematic-sites.txt) qui cacher le bouton d'abonnement.

Merci.

**Comment by Axelnm** [comment]
Nous avons également un problème avec une autre édition, mais cette fois,
pour l'affichage des images de nos articles :

https://www.varmatin.com/

Aucune illustration n'apparaît avec l'adblock.

Voulez-vous que j'ouvre un autre ticket ou pouvez-vous faire la modif?

Merci

*Axel Micheau*

*Chargé de Marketing DigitalPôle connaissance & **activation marketing*
*Bâtiment Unity - Grand Arénas, **06200 Nice*
*06 24 35 79 23*

<https://www.nicematin.com/>  <https://www.varmatin.com/>
<https://www.monacomatin.mc/>

   <http://nicematin.com/>   <http://varmatin.com/>
<http://monacomatin.mc/>
<https://www.linkedin.com/company/groupenicematin/mycompany/>
<https://twitter.com/Nice_Matin>   <https://www.facebook.com/Page.NiceMatin>

**Comment by smed79** [comment]
Aucune exception sur la **Liste FR** pour service de suivi, tracking, analytics, marketing, publicité ...
Pour afficher un numéro de téléphone vous n'avez pas besoin de passer par un service tiers.
