### ISSUE TITLE
varmatin.com

### ISSUE THREAD

**Issue by Axelnm** [easylist/listefr#31]
Bonjour,

La liste bloque les images sur notre site `https://www.varmatin.com/`.
Toutes les illustrations des articles ne s'affichent pas lorsque Adblock est activé.

Merci

**Comment by smed79** [comment]
Bonjour,

résolu https://github.com/easylist/listefr/commit/323d7ec1ab63e68c2e058dbc420ba45bd862a9a6

Merci pour le signalement.
