### ISSUE TITLE
abo.nicematin.com

### ISSUE THREAD

**Issue by Axelnm** [easylist/listefr#33]
Bonjour,

Dernière problématique sur notre site.

On utilise un outil d'AB testing, qui nous permets également de mettre en place des personnalisations ou informations sur notre site. Malheureusement tous les éléments sont bloqués avec l'Adblock.

Ci-joint un exemple avec et sans l'adblock, le numéro ajouté dans l'infobulle n'apparait pas.

Le tests peuvent être affichés sur toutes les pages du site, pas seulement sur `https://abo.nicematin.com/checkout`

adblockOFF
https://user-images.githubusercontent.com/96480761/147221586-25046e16-a305-45be-92f0-0a91d3a6cd3d.PNG

AdblockON
https://user-images.githubusercontent.com/96480761/147221591-2fdbd099-afb4-43d6-8969-afc9effae809.PNG

Merci beaucoup

**Comment by smed79** [comment]
https://github.com/easylist/listefr/issues/30#issuecomment-998932838
