### ISSUE TITLE
lesoir.be

### ISSUE THREAD

**Issue by JohnyP36** [easylist/listefr#38]
### URL
`https://www.lesoir.be/` *(the homepage)*

### Problem 
The box with videos gets blocked.

### Screenshot

https://user-images.githubusercontent.com/81161435/148176433-63d5deee-24e3-4c59-b4a9-ef10cee5253d.png

### Solution
```
lesoir.be#@##ultimedia_wrapper
```

##### See: https://github.com/easylist/easylistdutch/pull/27#:~:text=the%20to%20see.-,L5,-lesoir.be%23%40%23%23ultimedia_wrapper and https://github.com/easylist/easylistdutch/pull/27#issuecomment-1005749224

**Comment by smed79** [comment]
@ryanbr What do you think in this case ?
