### ISSUE TITLE
shop.lonelyplanet.com

### ISSUE THREAD

**Issue by ghost** [easylist/listefr#39]
Hi,

`lonelyplanet-weblinc.netdna-ssl.com`

breaks `https://shop.lonelyplanet.com/`

**Comment by smed79** [comment]
Bonjour, 

merci de donner plus de détails et comment reproduire le problème ?

**Comment by clavelc** [comment]
Bonjour,

La ligne ci-dessus de la listefr empêche la page ci-dessus de se charger correctement. Je ne sais pas trop quelle information rajouter :) 

La liste était chargée depuis NexrDNS

**Comment by smed79** [comment]
Je n'arrive pas à reproduire le problème (tester sous Adblock Plus / Firefox et Chromium)

Le soucis que vous nous signalez vient très probablement de NexrDNS qui bloque trop.
