### ISSUE TITLE
french-stream.run

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#47]
Block image popups at `https://s1.french-stream.run/`

Screenshot: 

https://user-images.githubusercontent.com/65717387/151542114-c0d786af-aec5-4a8a-bb3d-2775be69bee9.png

I believe all the `french-stream` domains can be included. 

https://user-images.githubusercontent.com/65717387/151982133-18634fa6-a044-4641-a956-8dba1f4452eb.png

**Comment by smed79** [comment]
> Block image popups

- https://github.com/abp-filters/abp-filters-anti-cv/pull/794
- https://github.com/easylist/listefr/commit/608ca6b179c7087df626c039e7d6f29ddb3e9ceb

> I believe all the french-stream domains can be included.

@felippesantos46 Post the list of domains here.

**Comment by smed79** [comment]
Closing ...
