### ISSUE TITLE
pop.work

### ISSUE THREAD

**Issue by manuel-martinez-dev** [easylist/listefr#5]
Hello,

### Problem:

All Links to `https://pop.work/` on external websites, such as articles or social networks, are being affected by a blocking rule on listeFR.

### Filters causing the issue:

* `://pop.*&$popup`
* `://pop.*?$popup`

### Example page:

As example, you can go to this website and try click on any of the links, they will not work because of the filters mentioned above.

* `https://www.linkedin.com/company/popdotwork/`

pop-upblocked https://user-images.githubusercontent.com/40897997/109807017-acd1d900-7c25-11eb-90fa-1ac3f199fc9c.png

_If an exception is added to the first filter, then the second one is triggered_

### Possible filter suggestion:

* `@@||pop.work*^$popup`

Thanks,

**Comment by smed79** [comment]
I update the filters https://github.com/easylist/listefr/commit/ff32734e81fa4f3bdf8acd9842cfb17426ba4bd3 to avoid false positive.

Please update your filter lists, test againt and tell me if the problem still there?

**Comment by manuel-martinez-dev** [comment]
Hello @smed79 thanks for fixing this issue.

I can confirm that the problem has been fixed.
