### ISSUE TITLE
kiosque.canardpc.com

### ISSUE THREAD

**Issue by Procyon-b** [easylist/listefr#52]
The devs are complaining in https://forums.lanik.us/viewtopic.php?t=47217 that one of the item is hidden. See https://kiosque.canardpc.com/home (3rd item/magazine cover)

That item is using a classname matching a generic cosmetic filter `##.pub468`

**Comment by smed79** [comment]
Corrigé ici https://forums.lanik.us/viewtopic.php?p=163201#p163201 (https://github.com/easylist/listefr/commit/aad7ee43a4289d6e46990a4a4b64b8ec94ee1cbe)

Merci.
