### ISSUE TITLE
wikimonde.com

### ISSUE THREAD

**Issue by Lakst2** [easylist/listefr#54]
Adblock provoque plusieurs dysfonctionnements sur ce site :

- L’autocomplétion de la recherche ne fonctionne pas sur le wiki : https://plus.wikimonde.com/wiki/Accueil
- En bas des articles, le texte « l'article d'origine » est normalement un lien mais pas avec adblock ce qui bloque le lien vers la source. https://wikimonde.com/article/Monica_Vitti
- Lorsqu'on clique sur une image, la page est complètement remplacée au lieu d'ouvrir une fenêtre interne.

Ces problèmes ont été corrigé avec AdGuard et uBlock Origin mais pas avec Adblock.
https://github.com/AdguardTeam/AdguardFilters/commit/da7642a00a208b75b9a5f8d6119b6d1a4b56f11c

**Comment by smed79** [comment]
Corrigé ... Merci pour le signalement.
