### ISSUE TITLE
guide-epargne.be

### ISSUE THREAD

**Issue by manuel-martinez-dev** [easylist/listefr#6]
Hello,

### Problem:

There was an issue with Easylist, that was blocking affiliate links on `https://www.guide-epargne.be/` (as well as sister site `https://www.spaargids.be/`), it seems that on Easylist the problem was fixed, but there is a popup filter on ListeFR that still blocks the popups on the page.

**See here the fix added to Easylist:**

https://github.com/easylist/easylist/commit/e6fa29a
https://github.com/easylist/easylist/commit/b54c9a9ca545ae2a57743035cbcfa9cb84bef523
https://github.com/easylist/easylist/commit/c9c1c1c3445bcf5a47bb15370577bbde1dec094b

### Filter causing the problem:

* `||serving-sys.com^$popup`

### Example page:

* `https://www.guide-epargne.be/epargner/tarifs-epargne.html`

popup-guide : https://user-images.githubusercontent.com/40897997/109809513-a729c280-7c28-11eb-9467-fff337fc5100.png

### Possible filter suggestion:

* `@@||serving-sys.com^$popup`

**Comment by smed79** [comment]
Fixed https://github.com/easylist/listefr/commit/ab646f4d979a8bb590dd35ec9964b5b7af532255

Thank you.
