### ISSUE TITLE
/images/sponsors/* est trop restrictif

### ISSUE THREAD

**Issue by olivierlemasle** [easylist/listefr#62]
Le filtre `/images/sponsors/*` est trop restrictif.

Les deux seules fois où j'ai remarqué que AdBlock Plus (utilisant la liste `listefr`) bloquait l'affichage normal d'une page, c'était en effet dû à ce filtre :

- La page https://getfedora.org/fr/sponsors/ s'affiche sans les logos des sponsors de Fedora, alors que c'est l'unique contenu informatif de cette page.
- La page d'accueil de Let's Encrypt (https://letsencrypt.org/) inclut une section "Major Sponsors and Funders" qui est vide parce que les logos des sponsors sont bloqués (j'ai signalé le problème à ABP : https://reports.adblockplus.org/e4162549-b50d-4322-8329-a55ab7ca63de)

Le filtre `/images/sponsors/*` a été ajouté en 2017 via le commit a44e25c986ea8966fefdb21489f0f2c241ef7508, pour le site http://laradieuse.com/. Cependant, si ce site utilisait en effet le terme "sponsor" pour "annonceur publicitaire", les pages Fedora et Let's Encrypt sont deux exemples importants montrant que le logo d'un sponsor n'a rien à voir avec de la publicité.

**Comment by smed79** [comment]
Bonjour,
filtre modifier https://github.com/easylist/listefr/commit/49b00c57fc27c72c3793a0f548409c73006e11e1 pour qu'il ne s'applique qu'au contenu tiers.

Merci pour le signalement.
