### ISSUE TITLE
Gamekult.com

### ISSUE THREAD

**Issue by noisegratte** [easylist/listefr#63]
Bonjour,

Url : `https://www.gamekult.com`

Le filtre sur `##div[data-ad-sticky-follow]` est trop restrictif et bloque l'affichage correct du header.

Sans filtre :

![image](https://user-images.githubusercontent.com/371864/156332302-6df045da-4765-4552-b8af-76b2b9c0bfc0.png)

Avec filtre :

![image](https://user-images.githubusercontent.com/371864/156332334-ff1170a4-c267-4115-85f0-c2d448b0899a.png)

Merci

**Comment by smed79** [comment]
Bonjour, 

c'est corrigé https://github.com/easylist/listefr/commit/5f699f54be5062eabaed5025d7e808ffb91f6aa8

Merci pour le signalement.
