### ISSUE TITLE
hitek.fr

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#64]
Sponsored articles at `https://hitek.fr/`

Screenshot:
<img width="403" alt="Screenshot 2022-03-03 at 10 56 29" src="https://user-images.githubusercontent.com/65717387/156541249-236c4e55-6cae-4d56-a14d-7caa9e7a2581.png">

**Comment by smed79** [comment]
Bonjour, 
je n'arrive pas à reproduire.

Si la publicité est affichée sur une page spécialisée, merci de poster le lien vers une page d'exemple.

**Comment by felippesantos46** [comment]
Hey @smed79, you are right i cannot reproduce again, probably my filters were not updated. 
We can close this one. 
Have a nice day !

**Comment by smed79** [comment]
Hi, 
I checked again and was able to reproduce https://i.imgur.com/VYYbVyQ.png

added https://github.com/easylist/listefr/commit/7a56b5190f7b64782b48d07431b4bb613a3f0be3

**Comment by felippesantos46** [comment]
@smed79 Thank you ! 😄
