### ISSUE TITLE
https://streaming-french.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#67]
Hide popups + image popups
<img width="1440" alt="Screenshot 2022-03-07 at 09 31 40" src="https://user-images.githubusercontent.com/65717387/156995511-0e16425c-e068-4b65-8f29-ee369be69272.png">
<img width="724" alt="Screenshot 2022-03-07 at 09 31 54" src="https://user-images.githubusercontent.com/65717387/156995553-ffc954a2-7e82-4fc3-890b-9293f616e0e1.png">

**Comment by smed79** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/pull/852
