### ISSUE TITLE
castorama.fr

### ISSUE THREAD

**Issue by jpocast** [easylist/listefr#69]
Bonjour, 

Nous sommes de l'équipe digital castorama. Récemment, vous avez ajouté dans votre liste : Le filtre : 

```
||media.castorama.fr/is/image/KingfisherDigital
```

Cet ajout bloque l'accès aux images de notre CDN pour l'ensemble des utilisateurs ayant des adblockers basés sur votre liste. 

Il ne s'agit pas de publicité mais des liens vers des pages internes.

Pouvez vous nous aider ? 

https://user-images.githubusercontent.com/101322463/157654769-17280d33-d7ea-450e-a3b0-81834f308b51.png

Merci

**Comment by jpocast** [comment]
Rebonjour, pouvez vous considérer notre demande ? 

Cela nous pénalise très fortement. 
Merci

**Comment by smed79** [comment]
Bonjour,

filtre supprimer ==> https://github.com/easylist/listefr/commit/dd9ab95b6426c48a13f7bb346f658d3897729501

Merci d'avoir pris le temps de le signaler.
