### ISSUE TITLE
french-stream.theproxy.how

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#75]
Popups / Banner at `http://french-stream.theproxy.how/`
<img width="1193" alt="Screenshot 2022-03-24 at 12 56 25" src="https://user-images.githubusercontent.com/65717387/159911228-d5a11654-a586-4027-9afc-aa4d9fef43d8.png">

**Comment by smed79** [comment]
https://github.com/easylist/easylist/pull/11502
https://github.com/easylist/easylist/pull/11504
https://github.com/abp-filters/abp-filters-anti-cv/pull/898
