### ISSUE TITLE
https://shahed4u.red/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/listefr#79]
Popup images at `https://shahed4u.red/`

Screenshot: 
<img width="715" alt="Screenshot 2022-03-29 at 10 59 35" src="https://user-images.githubusercontent.com/65717387/160574725-8a7f9ad6-906f-4d19-ac25-1f8fca692bd2.png">

**Comment by smed79** [comment]
https://github.com/easylist/listear/commit/f5d40dcb0eca8a64b7cd2d6182cff0ebf5f0a774
