### ISSUE TITLE
https://www.numerama.com/

### ISSUE THREAD

**Issue by momala454** [easylist/listefr#81]
`https://www.numerama.com/pop-culture/905135-disney-a-censure-des-scenes-violentes-de-falcon-et-le-soldat-de-lhiver.html`*

missing twitter integration

with adblock:
![image](https://user-images.githubusercontent.com/83005/161020163-8ec20b79-dc9d-4f00-b166-153569e971da.png)

without:
![image](https://user-images.githubusercontent.com/83005/161020206-af9e6384-feaa-4c19-9916-613c2c3f30c2.png)

edit: it looks like  `https://cache.consentframework.com/` and `https://choices.consentframework.com/` must be allowed, but this bring back the cookie popup.
The twitter widget is added on the script `https://choices.consentframework.com/js/pa/22805/c/xDJmn/cmp` in the function `_addTagListeners`. I wonder if it's possible for ublock to modify the script on the fly to only execute the callback, or something ?

**Comment by momala454** [comment]
similar problem with consentframework on `https://www.frandroid.com/marques/apple/1191269_le-gros-probleme-dapple-derriere-lescroquerie-ampme-sur-iphone`

**Comment by smed79** [comment]
Le soucis que vous nous signalez n'a apparemment pas de rapport avec la **Liste FR**.

Très probablement vous avez la liste sociale activé dans votre bloqueur de publicités.
