### ISSUE TITLE
p77.(...).tiktokcdn.com

### ISSUE THREAD

**Issue by MaXfAa** [easylist/listefr#87]
C'est plus une question qu'un problème/une suggestion mais:
- Pourquoi est-ce que ces domaines de TikTok sont bloqués ? (J'ai pas l'impression qu'ils soient liés aux pubs sur TikTok)
- Pourquoi êtes-vous la seul liste à les bloquer ?
- Pourquoi ne pas bloquer les autres domaines extrêmement similaires (screenshot n°2) ?

https://user-images.githubusercontent.com/71935156/162997946-38d84f63-cb2d-4abc-b1ec-68fe51acc2e9.png

https://user-images.githubusercontent.com/71935156/162998015-55258108-a30a-4a7c-941c-8cbe92abdc4d.png

**Comment by smed79** [comment]
Aucun domaine TikTok n'est bloqué par la **Liste FR**. 
Très probablement c'est votre adblock qui interprète mal une règle.

**Comment by smed79** [comment]
Continuer ici https://t.ly/ZKoX
