### ISSUE TITLE
b2cproductionsite-be80wkthrgjjkmzuip0.netdna-ssl.com

### ISSUE THREAD

**Issue by MaXfAa** [easylist/listefr#88]
`b2cproductionsite-be80wkthrgjjkmzuip0.netdna-ssl.com` ne devrait pas être bloqué car certaines images sur le sites d'Orange ne chargent pas (et je ne pense pas qu'il soit utilisé pour de la pub).

Avec ce domaine bloqué:
https://user-images.githubusercontent.com/71935156/163730688-286c429e-9d6a-4c57-9418-594ec2dc0be5.jpeg

En whitelistant ce domaine:
https://user-images.githubusercontent.com/71935156/163730698-7af2eb77-5e6d-4c16-86fd-f853cb968125.jpeg

**Comment by smed79** [comment]
Page exemple ?

**Comment by MaXfAa** [comment]
> Page exemple ? 

https://www.orange.be/fr

**Comment by smed79** [comment]
La seule image de bloc pour moi est 
- `https://b2cproductionsite-be80wkthrgjjkmzuip0.netdna-ssl.com/sites/b2c/files/image_go_exteme_banner.png` 
- https://imgur.com/6wslhr6.png

Merci générer un [rapport](https://help.eyeo.com/en/adblockplus/report-an-issue?) Adblock Plus et poster le lien ici.

**Comment by MaXfAa** [comment]
> La seule image de bloquer pour moi est
> - `b2cproductionsite-be80wkthrgjjkmzuip0.netdna-ssl.com/sites/b2c/files/image_go_exteme_banner.png` (https://github.com/easylist/listefr/commit/a660e0f8538d7e416c87d573efc6a871ca7eab2b)
> - https://imgur.com/6wslhr6.png
> 
> Merci générer un [rapport](https://help.eyeo.com/en/adblockplus/report-an-issue?) Adblock Plus et poster le lien ici.

Je ne peux pas générer de rapport Adblock Plus puisque j'utilise votre liste dans ma config NextDNS
