### ISSUE TITLE
https://www.ecranlarge.com/series/946024-westworld/1431703-saison-4/1436549-westworld-saison-4-episode-1-critique-du-comeback

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listefr#96]
### Issue
Background ad and ad placeholders (top and in-content ads) on 

- `https://www.ecranlarge.com/series/946024-westworld/1431703-saison-4/1436549-westworld-saison-4-episode-1-critique-du-comeback`
- https://user-images.githubusercontent.com/57706597/176137437-f33cd50e-f72d-4aa7-98b4-1914cdd93540.png
- https://user-images.githubusercontent.com/57706597/176137446-1856bed4-c965-42d4-a6f2-b3c957f5b54a.png

### Suggested filters:
`/proxy/bg.php?$script,domain=ecranlarge.com `
`ecranlarge.com##.top-banner`
`ecranlarge.com##.cgIncontentSlot`

**Comment by sabinahschmitz** [comment]
Hi @smed79 could you have a look at this issue please? Thank you!

**Comment by smed79** [comment]
Hi, 
sorry for the delay reply... 

added https://github.com/easylist/listefr/commit/dfc6d47a8b013c75cdf2faef2495b6d7ca619e20

Thank you.

**Comment by edivaniadc** [comment]
> ecranlarge.com##.cgIncontentSlot
Hi @smed79 can you please also add `ecranlarge.com##.cgIncontentSlot` to hide the incontent-ad between text.

**Comment by smed79** [comment]
Example page, screenshot ?
