### ISSUE TITLE
Sponsored content on manomano . fr

### ISSUE THREAD

**Issue by manuel-martinez-dev** [easylist/listefr#97]
### Website:

`manomano . fr`

## Example page:

`https://www.manomano.fr/applique-murale-salon-et-entree-179`

## Problem:

_"Sponsored"_ content shows up on search results.

<details>
![manoSponsored](https://user-images.githubusercontent.com/40897997/182710743-629db9d0-48d8-45dd-84d0-d995d71f183d.JPG)
</details>

## Filter suggestion:

The following filter seems to do the trick and it does not hide any other content.

`manomano.fr##a[class*="sponsoredProductCard"]`

**Comment by smed79** [comment]
Fixed in https://github.com/easylist/listefr/commit/3ce94c827800064ce619e16495b27b7a3b30111b

Thank you.

**Comment by smed79** [comment]
- `manomano.co.uk##a[class*="sponsoredProductCard"]`

@ryanbr 

- `manomano.de##a[class*="sponsoredProductCard"]`
- `manomano.it##a[class*="sponsoredProductCard"]`

@Khrin 

- `manomano.es##a[class*="sponsoredProductCard"]`

@felippesantos46
