### ISSUE TITLE
danielmaghen.com

### ISSUE THREAD

**Issue by locustAbjector** [easylist/listefr#99]
## ISSUE:

A self promo banner is being hidden it is not an external ad.

### Screenshot:

![hidden ad](https://user-images.githubusercontent.com/114186776/191835346-81bbd1ab-7d81-4b12-8004-9314fa61578a.JPG)

## Lists:

* listeFR
* Easyprivacy
* ABP filters
* Fanboy's Notifications Blocking List
* Fanboy's Social Blocking List
* I don't care about cookies
* Peter Lowe's list

### OTHER:

The following filter seems to be one causing the issue

`###publicite`

Is it possible to allow it, or ad an exception for this website?.

thanks,

**Comment by locustAbjector** [comment]
En fait, je suis juste un utilisateur qui est tombé sur ce site par hasard... mais si vous jugez qu'il n'est pas possible de le consentir, ce serait bien moi.

Je voulais simplement le signaler :)

merci pour votre réponse

**Comment by smed79** [comment]
J'ai ajouté une exception https://github.com/easylist/listefr/commit/6d4c81bad21fb0f3293ded6d0ea3ebddd92eaa42 en attendant que le webmaster remplace le nom de la div par quelque chose qui n'a pas rapport avec la publicité.

Merci pour le signalement.
